# Generated by Django 5.0.7 on 2024-07-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
